---
{{- if .Values.appSsmSecrets }}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.applicationName }}-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  backendType: systemManager
  data:
    {{- range .Values.appSsmSecrets }}
    - key: {{ .path }}
      name: {{ .environment_variable | lower | replace "_" "-" }}
    {{- end }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.applicationName }}-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  refreshInterval: "15m"
  data:
    {{- range .Values.appSsmSecrets }}
    - remoteRef:
        key: {{ .path }}
      secretKey: {{ .environment_variable | lower | replace "_" "-" }}
    {{- end }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: main-external-secrets
  target:
    name: {{ .Values.applicationName }}-secrets
    template:
      metadata:
        labels:
          {{- include "labels" . | nindent 10 }}
{{- end }}
