apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.applicationName }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
      app: {{ .Values.applicationName }}
  ports:
  - port: {{ .Values.port }}
