apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deepface-cobli
  name: deepface-cobli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deepface-cobli
  template:
    metadata:
      labels:
        app: deepface-cobli
    spec:
      containers:
        - image: 911383825788.dkr.ecr.us-east-1.amazonaws.com/cobli-internal/deepface:d0e082bc570551529d3aa78543eef11ca933c862
          ports:
          - containerPort: 5000
          name: deepface-cobli
          resources:
            requests:
              cpu: 3500m
              memory: 27Gi
              nvidia.com/gpu: 1
            limits:
              cpu: 3500m
              memory: 27Gi
              nvidia.com/gpu: 1
      tolerations:
        - key: cobli.co/workload
          operator: "Equal"
          value: gpgpu
          effect: "NoSchedule"
      restartPolicy: Always
